project:
  type: website

website:
  title: "Notes on Exam 6U"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Regulation
        menu:
          - text: History
            href: history.qmd
          - text: NAIC
            href: naic.qmd
      - text: Statutory
        menu:
          - href: statutory.qmd
            text: Statutory
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

